// src/lib/supabase/database.types.ts
// Auto-generated by: supabase gen types typescript --linked
// Run `npm run db:types` after making schema changes.
// Manual baseline until the Supabase CLI generates this from your project.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          role: Database['public']['Enums']['user_role'];
          department: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: Database['public']['Enums']['user_role'];
          department?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      services: {
        Row: {
          id: string;
          slug: string;
          title: string;
          division: string;
          tagline: string | null;
          description: string;
          icon: string | null;
          color: string | null;
          features: Json;
          benefits: Json;
          process: Json;
          image: string | null;
          display_order: number;
          status: string;
          seo_title: string | null;
          seo_description: string | null;
          seo_keywords: Json;
          created_at: string;
          updated_at: string;
          published_at: string | null;
          deleted_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['services']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['services']['Insert']>;
      };
      projects: {
        Row: {
          id: string;
          slug: string;
          title: string;
          client: string;
          category: string;
          description: string;
          short_description: string | null;
          image: string | null;
          gallery: Json;
          technologies: Json;
          impact: Json | null;
          testimonial: Json | null;
          service_division: string | null;
          featured: boolean;
          status: string;
          start_date: string | null;
          completed_at: string | null;
          url: string | null;
          created_at: string;
          updated_at: string;
          published_at: string | null;
          deleted_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['projects']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['projects']['Insert']>;
      };
      blog_posts: {
        Row: {
          id: string;
          slug: string;
          title: string;
          excerpt: string | null;
          content: string;
          author_id: string | null;
          author_name: string;
          cover_image: string | null;
          tags: Json;
          category: string;
          status: string;
          scheduled_at: string | null;
          published_at: string | null;
          read_time: number | null;
          featured: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['blog_posts']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['blog_posts']['Insert']>;
      };
      people: {
        Row: {
          id: string;
          slug: string;
          category: string;
          full_name: string;
          title: string;
          department: string | null;
          bio: string;
          short_bio: string | null;
          photo: string | null;
          email: string | null;
          phone: string | null;
          location: string | null;
          joined_at: string | null;
          skills: Json;
          certifications: Json;
          social_links: Json;
          projects: Json;
          articles: Json;
          display_order: number;
          featured: boolean;
          active: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['people']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['people']['Insert']>;
      };
      testimonials: {
        Row: {
          id: string;
          quote: string;
          author_name: string;
          author_role: string | null;
          author_organization: string | null;
          author_avatar: string | null;
          rating: number;
          project_id: string | null;
          service_id: string | null;
          featured: boolean;
          status: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['testimonials']['Row'], 'id' | 'created_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['testimonials']['Insert']>;
      };
      talent_profiles: {
        Row: {
          id: string;
          full_name: string;
          email: string;
          phone: string | null;
          bio: string | null;
          avatar: string | null;
          skills: Json;
          experience: number | null;
          experience_level: string | null;
          portfolio: string | null;
          resume_url: string | null;
          availability: string;
          verification_status: string;
          categories: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['talent_profiles']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['talent_profiles']['Insert']>;
      };
      applications: {
        Row: {
          id: string;
          type: string;
          applicant_name: string;
          email: string;
          phone: string | null;
          subject: string | null;
          message: string | null;
          role: string | null;
          skills: Json;
          portfolio: string | null;
          status: string;
          assignee_id: string | null;
          notes: Json;
          history: Json;
          submitted_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['applications']['Row'], 'id' | 'submitted_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['applications']['Insert']>;
      };
      faqs: {
        Row: {
          id: string;
          question: string;
          answer: string;
          category: string;
          display_order: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['faqs']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['faqs']['Insert']>;
      };
      announcements: {
        Row: {
          id: string;
          title: string;
          content: string;
          type: string;
          priority: string;
          audience: string;
          status: string;
          scheduled_at: string | null;
          published_at: string | null;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['announcements']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['announcements']['Insert']>;
      };
      partners: {
        Row: {
          id: string;
          organization_name: string;
          contact_person: string;
          email: string;
          phone: string | null;
          website: string | null;
          logo: string | null;
          industry: string | null;
          description: string | null;
          status: string;
          partnership_type: string;
          partnership_start_date: string | null;
          partnership_end_date: string | null;
          address: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['partners']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['partners']['Insert']>;
      };
      media_folders: {
        Row: {
          id: string;
          name: string;
          parent_id: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['media_folders']['Row'], 'id' | 'created_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['media_folders']['Insert']>;
      };
      media: {
        Row: {
          id: string;
          name: string;
          file_name: string;
          url: string;
          mime_type: string;
          size_bytes: number;
          width: number | null;
          height: number | null;
          folder_id: string | null;
          uploaded_by: string | null;
          alt_text: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['media']['Row'], 'id' | 'created_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['media']['Insert']>;
      };
      site_settings: {
        Row: {
          id: string;
          key: string;
          value: Json;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['site_settings']['Row'], 'id' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['site_settings']['Insert']>;
      };
      impact_stats: {
        Row: {
          id: string;
          projects_completed: number;
          youth_empowered: number;
          communities_served: number;
          client_satisfaction: number;
          active_members: number;
          events_hosted: number;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['impact_stats']['Row'], 'id' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['impact_stats']['Insert']>;
      };
      contact_submissions: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string | null;
          subject: string;
          message: string;
          type: string;
          status: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['contact_submissions']['Row'], 'id' | 'created_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['contact_submissions']['Insert']>;
      };
      partnership_requests: {
        Row: {
          id: string;
          organization_name: string;
          contact_person: string;
          email: string;
          phone: string | null;
          partnership_type: string;
          message: string;
          status: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['partnership_requests']['Row'], 'id' | 'created_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['partnership_requests']['Insert']>;
      };
      audit_logs: {
        Row: {
          id: string;
          actor_id: string | null;
          actor_name: string;
          action: string;
          resource_type: string;
          resource_id: string | null;
          resource_name: string | null;
          changes: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['audit_logs']['Row'], 'id' | 'created_at'> & { id?: string };
        Update: never;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role:
        | 'growthbridge_super_admin'
        | 'growthbridge_admin'
        | 'growthbridge_content_manager'
        | 'growthbridge_project_manager'
        | 'growthbridge_recruiter'
        | 'growthbridge_analyst';
    };
  };
};
